Enable Goodman-Kruskal lambda
jasp-stats/jaspFrequencies pull request #9
Opened 2020-11-25 11:02 UTC by Kucharssim

Fixes https://github.com/jasp-stats/jasp-issues/issues/1075

Also comes with a verified unit test.

2020-12-07 14:06 UTC, vandenman requested changes
So this looks fine to me. The only thing I noticed is that all Lambdas are always 0 if there is a 2 by 2 design. That could be correct but I don't know this topic well enough.

2020-12-07 16:42 UTC, Kucharssim commented on R/contingencytables.R
> +    nc <- ncol(counts.matrix)
Yeah, my bad

2020-12-07 16:48 UTC, Kucharssim commented
> The only thing I noticed is that all Lambdas are always 0 if there is a 2 by 2 design. That could be correct but I don't know this topic well enough.

It's not caused by 2x2 design, but is a general limitation of the coefficient. From Kvålseth (2017):
![Screenshot 2020-12-07 at 17 43 37](https://user-images.githubusercontent.com/7093546/101378887-ea87c580-38b3-11eb-9b67-f27623eaaa05.png)

The example on Wiki also shows this: https://en.wikipedia.org/wiki/Goodman_and_Kruskal%27s_lambda#Weaknesses

2020-12-08 07:57 UTC, vandenman approved these changes

2020-12-08 10:39 UTC, TimKDJ commented
Thanks for reviewing @vandenman, it's a little tricky to stay on top of things in my limited time

2020-12-08 10:39 UTC, merged